version: '3.4'

services:
  # CATALOG API #
  catalogdb:
    container_name: catalog.mongo-db
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db # default filesystem for mongo is data/db, map it to our volume

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017" # override appsettings.json value
    depends_on:
      - catalogdb
    ports:
      - "8000:80" # expose 80 container port to external 8000
  
  # BASKET API #
  basketdb:
    container_name: basket.redis-cache
    restart: always
    ports:
      - "6379:6379" 

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Redis=basketdb:6379" # override appsettings.json value
      - "GrpcSettings__DiscountServiceUrl=http://discount.grpc" # cross-service communcation with discount grpc
    depends_on:
      - basketdb
    ports:
      - "8001:80" # expose 80 container port to external 8001

  # DISCOUNT API #
  discountdb:
    container_name: discount.postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/posgtesql/data/

  pgadmin:
    container_name: discount.postgres-db-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com # login for Postgres UI 
      - PGADMIN_DEFAULT_PASSWORD=admin1234 # pass for Postgres UI
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"  # expose 80 container port to external 8002

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"  # expose 80 container port to external 8003


  # ORDERING API #
  orderdb:
    container_name: ordering.mssql-db
    restart: always
    environment:
      - SA_PASSWORD=Jko3va-D9821jhsvGD
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrdersConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Jko3va-D9821jhsvGD;"
    depends_on:
      - orderdb
    ports:
      - "8004:80"
  
  # QUEUE (MESSAGE BROKER) -> FROM BASKET TO ORDER DURING CHECKOUT BASKET #
  rabbit-queue:
    container_name: rabbitmq-broker
    restart: always
    ports:
      - "5672:5672" # rabbitmq port
      - "15672:15672" # rabbitmq dashboard
