version: '3.4'

services:
  # CATALOG API #
  catalogdb:
    image: mongo:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  # BASKET API #
  basketdb:
    image: redis:alpine
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  # DISCOUNT API #
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
